### PR TITLE
feat: add multiple resource types as food

### PR DESCRIPTION
**Pull request by deggja**
Let the snek eat resource types:

Pod
Deployment
Service
Job
ConfigMap
Secret
StatefulSet
DaemonSet
PersistentVolume
PersistentVolumeClaim
ServiceAccount
NetworkPolicy

This might be too much.

### CODE REVIEW

**Comment by alphabet5** [comment]
Could you also include nodes? Thanks so much, this is the feature I need before shipping to prod.

**Comment by deggja** [comment]
> Could you also include nodes? Thanks so much, this is the feature I need before shipping to prod.

Of course. Just waiting for someone to ask to be honest.

**Comment by JJGadgets** [comment]
The following resources should also be added: CephCluster, all CrunchyData + CNPG + Zalando Postgres clusters, ExternalSecrets, all Flux + Argo CRs, and VolSync.

**Comment by deggja** [comment]
> The following resources should also be added: CephCluster, all CrunchyData + CNPG + Zalando Postgres clusters, ExternalSecrets, all Flux + Argo CRs, and VolSync.

Great suggestion. I'll definitely look into this as well as deleting the cluster CNI.

**Comment by jordansimmons25** [comment]
Namespaces too? 👀

**Comment by deggja** [comment]
> Namespaces too? 👀

Say less. Idk how I could forget.

**Pull request closed without merging**
